version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mapog
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
