name: Deploy Backend to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Lint and test
        run: |
          npm run lint
          npm test

      - name: Build Docker image
        run: docker build -t mapog-backend .

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        with:
          service: ${{ secrets.RAILWAY_SERVICE_ID }}
          token: ${{ secrets.RAILWAY_API_TOKEN }}
