name: Auto Build & Push Docker Images (Backend)

on:
  push:
    branches:
      - main

jobs:
  docker-build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Auto Version Bump
        run: |
          npm version patch --no-git-tag-version
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "ci: bump version [skip ci]" || echo "No changes"
          git push

      - name: Extract version
        id: version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            -t mapog/backend:${{ env.VERSION }} \
            -t mapog/backend:latest \
            .
          docker push mapog/backend:${{ env.VERSION }}
          docker push mapog/backend:latest
